In [ ]:
import numpy as np

mat = np.array([
    [8, 1, 6],
    [3, 5, 7],
    [4, 9, 3]
])
#target_sum = np.sum(mat)
row_sums = np.sum(mat, axis=1)
print(row_sums)


[15 17 16]


In [33]:
np.all(np.array([9, 7, 9]) == 9)

np.False_

In [ ]:
import numpy as np

d =np.array( [ 
    2,3,4,
    5,6,2
] )

j =np.array( [ 
    True,True,False
] )

print(np.all(d))
print(np.all(j))


True
False


In [93]:
import numpy as np
#np.array([1,2,3,4,5])
#np.arange(107,120)# видає рангі карт
#np.arange(7,15)+200
d = np.array([np.arange(7,15)+100, np.arange(7,15)+200, np.arange(7,15)+300, np.arange(7,15)+400])#двумерний масив с рартами по масти
d = d.flatten()#плоский масив с колодой картю
#print(d)
#print(np.random.permutation(d))
s = np.random.permutation(d)
print(s)
player = s[:3]
s = s[3:]
print(s)
player002 = s[:3]
s = s[3:]
print("колода", s)
print(player)
print(player002)





[213 308 108 307 212 113 413 414 313 211 111 209 210 207 312 310 208 109
 114 408 309 412 112 314 410 110 411 214 107 311 409 407]
[307 212 113 413 414 313 211 111 209 210 207 312 310 208 109 114 408 309
 412 112 314 410 110 411 214 107 311 409 407]
колода [413 414 313 211 111 209 210 207 312 310 208 109 114 408 309 412 112 314
 410 110 411 214 107 311 409 407]
[213 308 108]
[307 212 113]


In [146]:
import numpy as np
# несколоко колод карт

num_players = 4   # кількість гравців
num_cards = 3     #кількість розданих карт 
num_decks = 5

num_decks = np.array([np.arange(7,15)+100, np.arange(7,15)+200, np.arange(7,15)+300, np.arange(7,15)+400])#двумерний масив с рартами по масти
num_decks = num_decks.flatten()#плоский масив с колодой картю
s = np.random.permutation(num_decks)
print(s)


for i in range(num_players):
    player = s[:num_cards]   # беремо перші k карт
    s = s[num_cards:]        # зменшуємо колоду
    print(f"Гравець {i+1} отримав:", player)
    print("Залишок у колоді:", s)


[411 212 110 207 312 209 113 111 310 114 412 308 112 307 211 413 314 408
 210 309 410 208 214 409 313 213 414 407 108 109 311 107]
Гравець 1 отримав: [411 212 110]
Залишок у колоді: [207 312 209 113 111 310 114 412 308 112 307 211 413 314 408 210 309 410
 208 214 409 313 213 414 407 108 109 311 107]
Гравець 2 отримав: [207 312 209]
Залишок у колоді: [113 111 310 114 412 308 112 307 211 413 314 408 210 309 410 208 214 409
 313 213 414 407 108 109 311 107]
Гравець 3 отримав: [113 111 310]
Залишок у колоді: [114 412 308 112 307 211 413 314 408 210 309 410 208 214 409 313 213 414
 407 108 109 311 107]
Гравець 4 отримав: [114 412 308]
Залишок у колоді: [112 307 211 413 314 408 210 309 410 208 214 409 313 213 414 407 108 109
 311 107]


In [ ]:
import numpy as np
# 
# приклад з tile
#d = None
d =np.array([1,2,3,4,5,6,7,8])
g= np.tile(d,(10,1))
s = np.array([np.random.permutation(a) for a in g])
print(s)
print(s[:,:3])
print(s[:,3:])


a =np.array([[1],[2],[3]])
#print(np.random.permutation(a))

[[4 1 6 3 2 8 5 7]
 [5 8 2 7 3 1 4 6]
 [1 7 4 6 5 3 2 8]
 [6 4 2 7 8 3 5 1]
 [4 1 7 8 3 2 6 5]
 [6 7 3 1 5 2 4 8]
 [1 8 6 4 3 2 5 7]
 [6 2 5 1 8 4 7 3]
 [5 3 4 8 2 7 6 1]
 [8 1 7 3 2 5 4 6]]
[[4 1 6]
 [5 8 2]
 [1 7 4]
 [6 4 2]
 [4 1 7]
 [6 7 3]
 [1 8 6]
 [6 2 5]
 [5 3 4]
 [8 1 7]]
[[3 2 8 5 7]
 [7 3 1 4 6]
 [6 5 3 2 8]
 [7 8 3 5 1]
 [8 3 2 6 5]
 [1 5 2 4 8]
 [4 3 2 5 7]
 [1 8 4 7 3]
 [8 2 7 6 1]
 [3 2 5 4 6]]


In [ ]:
def case_1 (hand_numbers):    
    suits = hand_numbers // 100     # масть карти
    
    # Друкуємо масті карт
    # for s in suits:
    #     if s == 1:
    #         print("піки")
    #     elif s == 2:
    #         print("череві")
    #     elif s == 3:
    #         print("бубни")
    #     elif s == 4:
    #         print("трефи")
    #     else:
    #         print("невідома масть")
    
    print(suits)
    # Перевірка на "каре" (4 карти одного рангу)
    uniq_values, counts = np.unique(suits, return_counts=True)
    print(uniq_values, counts)
    return np.any(counts >= 4)

# Приклади
test1 = np.array([207, 214, 221, 228, 215])  # однакові гідності
hand2 = np.array([207, 207, 407, 307, 207])  # різні гідності

print("Hand1:", case_1(test1))  
print("Hand2:", case_1(hand2))

[2 2 2 2 2]
[2] [5]
Hand1: True
[2 2 4 3 2]
[2 3 4] [3 1 1]
Hand2: False


In [ ]:
import numpy as np 
a = np.array([207, 214, 221, 228, 215]) 
print(a.size)# в нумпай, або тут в компюторі на lean виводить помилку, то я замінила на size ЦЕ ТАКОЖ функція яка визначає кількість елементів 
print(a)
print(a//100)
print(np.unique(a//100))



5
[207 214 221 228 215]


AttributeError: 'numpy.ndarray' object has no attribute 'length'

In [ ]:
import numpy as np 

a = np.array([207, 214, 221, 228, 215]) 

suits = np.unique(a // 100)

for s in suits:
    if s == 1:
        print("бубни")
    elif s == 2:
        print("черви")
    elif s == 3:
        print("трефи")
    elif s == 4:
        print("піки")


черви


In [20]:
import numpy as np 

a = np.array([207, 214, 221, 228]) 
b = np.array([False, False, False, True])

print(a)
print(a[b])
s = b[b]
print(s)
print(a.size)
print(s.size)
print(s.size/a.size)



[207 214 221 228]
[228]
[ True]
4
1
0.25


In [ ]:
import numpy as np 
# проходиться по масиву й числа монотонно зростає 
# просртувати від меншого к більшому монотонно зростаючи на 1
def case_2(hand_numbers):
    suit = hand_numbers // 100      # визначає масть карти
    ranks = hand_numbers % 100      # гідність карт (2–14)
    
    uniq_values, counts = np.unique(ranks, return_counts=True) and np.unique(suit, return_counts=True)
    hand2.sort()


    print("масть:", suit)
    print("ранг:", ranks)
    print("унікальний ранг:", uniq_values)
    print("кількість кожного рангу(скільки всього):", counts)

    
    return np.any(counts == 4) and np.any(counts == 5)



# Приклади
test1 = np.array([207, 208, 209, 210, 211])  # однакові гідності
hand2 = np.array([207, 207, 407, 307, 207])  # різні гідності



print("Hand1:", case_2(test1))  
print("Hand2:", case_2(hand2))

масть: [2 2 2 2 2]
ранг: [ 7  8  9 10 11]
унікальний ранг: [2]
кількість кожного рангу(скільки всього): [5]
Hand1: False
масть: [2 2 4 3 2]
ранг: [7 7 7 7 7]
унікальний ранг: [2 3 4]
кількість кожного рангу(скільки всього): [3 1 1]
Hand2: False


In [ ]:
import numpy as np 
# проходиться по масиву й числа монотонно зростає 

def case_2 (hand_numbers):    
    suits = hand_numbers //100     # масть карти
    
    print(suits)
    # Перевірка на "каре" (4 карти одного рангу)
    uniq_values, counts = np.unique(suits, return_counts=True)
    print(uniq_values, counts)
    return np.any(counts == 5)

    


# Приклади
test1 = np.array([207, 208, 209, 210, 211])  # однакові гідності
hand2 = np.array([208, 214, 407, 307, 209])  # різні гідності

print("Hand1:", case_1(test1))  
print("Hand2:", case_1(hand2))

NameError: name 'case_1' is not defined

In [ ]:
import numpy as np 
# проходиться по масиву й числа монотонно зростає 
# просртувати від меншого к більшому монотонно зростаючи на 1
def case_2(hand_numbers):
    suit = hand_numbers // 100      # визначає масть карти 
    ranks = hand_numbers % 100      # гідність карт (2–14)
        
    print(hand2 //100 == 3) 
    print( test1[   test1 // 100 == 3])
    print(test1//100)
    pattern1 = np.array([3])

    result = np.isin(pattern1,test1//100).all()
    print(result)   # True



# Приклади
test1 = np.array([311, 107, 407, 208, 310])  # однакові гідності
hand2 = np.array([207, 107, 407, 208, 207])  # різні гідності
print(test1 // 100 == 2) 
print( test1[   test1 // 100 == 2])

m2=test1[   test1 // 100 == 2]
m3=test1[   test1 // 100 ==3 ]
m4=test1[   test1 // 100 == 4]
m1=test1[   test1 // 100 == 1]
print(m1,m2,m3,m4)




print("Hand1:", case_2(test1))  
print("Hand2:", case_2(hand2))

[False False False  True False]
[208]
[107] [208] [311 310] [407]
False


In [ ]:
import numpy as np 
test1 = np.array([311, 307, 309, 308, 310])
sort = np.sort(test1)
print(sort) 
d = [1, 2, 3, 4, 5]
print(sort - d) 

[307 308 309 310 311]
[306 306 306 306 306]


In [ ]:
import numpy as np 

# Приклади
test1 = np.array([311, 112, 407, 213, 314])  # однакові гідності
hand2 = np.array([207, 107, 407, 208, 207])  # різні гідності

print(hand2 //100 == 3) 
print( test1[   test1 // 100 == 3])
print(test1//100)
pattern1 = np.array([3])

result = np.isin(pattern1,test1//100).all()
print(result)   # True


[False False False False False]
[311 314]
[3 1 4 2 3]
True


In [ ]:
import numpy as np 

test1 = np.array([108,208,308,408 ])  
test2 = np.array([311, 112, 407, 213, 314, 413, 209, 111, 107, 414,411, 412])
    
def case_2(hand_numbers):
    #начало
    # розкладуемо масів по мастям
    m2=hand_numbers[ hand_numbers // 100 == 2]
    m3=hand_numbers[ hand_numbers // 100 == 3]
    m4=hand_numbers[ hand_numbers // 100 == 4]
    m1=hand_numbers[ hand_numbers // 100 == 1]
    # ви значити козрь
    # козрь є масть в якої сума рангів найбільша
    # сформувати масів рангів карт в розрізі мастей
    m = np.array([
        # сума рангів карт першої масті
        np.sum(m1%100),
        np.sum(m2%100),
        np.sum(m3%100),
        np.sum(m4%100) 
    ])
    arg_max = np.argmax(m) # повертае індекс найбільшого елементу масиву
    cart = hand_numbers[ hand_numbers // 100 == arg_max +1 ]

    print(f" МАСІВ КОЗИРНИХ КАРТ{cart}")


    pattern4 = np.array([11,12,13,14])
    results = np.isin(pattern4,cart%100).all()
    print(f" DDDD {results}")
    return results
    # конец

print("Hand3:", case_2(test2))  


 МАСІВ КОЗИРНИХ КАРТ[407 413 414 411 412]
 DDDD True
Hand3: True


In [ ]:
#розбиваемо карти по мастям на 4 масиви (є)
#визначити козрь - це така масть в якої сума рангів карт є найбільшою(є)
#для масиву з козерними катрамі перевірити наявність 4 карт(туз, король, дама, валет)
# 

# функция якій передаються всі карти(hand_numbers) гравця, індекс масті та набор карти для перевірки 

#Треба також мати всі старші карти в усіх інших наявних мастях 


In [ ]:
import numpy as np 

test1 = np.array([108,208,308,408 ])  
test2 = np.array([311, 112, 213, 314, 413, 209, 111, 107, 414,411, 412])
test3 = np.array([313, 113, 407, 213, 314, 413, 214, 114, 107, 414,411, 412])


def get_trump_index(hand_numbers):
    #начало
    # розкладуемо масів по мастям
    m1=get_cards_by_suit(hand_numbers,1)
    m2=get_cards_by_suit(hand_numbers,2)
    m3=get_cards_by_suit(hand_numbers,3)
    m4=get_cards_by_suit(hand_numbers,4)
     # ви значити козрь
    # козрь є масть в якої сума рангів найбільша
    # сформувати масів рангів карт в розрізі мастей
    m = np.array([
        # сума рангів карт першої масті
        np.sum(m1%100),
        np.sum(m2%100),
        np.sum(m3%100),
        np.sum(m4%100) 
    ])
    arg_max = np.argmax(m) # повертае індекс найбільшого елементу масиву
    return arg_max +1



def get_cards_by_suit(hand_numbers, suit_index):
    return hand_numbers[ hand_numbers // 100 == suit_index]

def check_pattern(hand_numbers, suit_index, pattern):
    suit_carts = hand_numbers[ hand_numbers // 100 == suit_index]

    # Перевірка pattern
    ranks = suit_carts % 100
    print("Ранги карт:", ranks)

    #pattern4 = np.array([11,12,13,14])
    results = np.isin(pattern, ranks).all()
    print(f" DDDD {results}")
    return results
    # конец



# hand_numbers — усі карти гравця , mast_index — номер масті (1,2,3,4) , pattern — набір рангів, які треба перевірити
def case_2(hand_numbers):

    pattern4 = np.array([11,12,13,14])
    pattern2 = np.array([14,13])

    trump_index = get_trump_index(hand_numbers)
    results = check_pattern(hand_numbers,trump_index , pattern4)

    if trump_index != 1:
        results5 = check_pattern(hand_numbers,1, pattern2)
    if trump_index != 2:
        results5 = check_pattern(hand_numbers,2, pattern2)
    if trump_index != 3:
        results5 = check_pattern(hand_numbers,3, pattern2)
    if trump_index != 4:
        results5 = check_pattern(hand_numbers,4, pattern2)
    

    return results
    # конец

def case_3(hand_numbers):
    pattern4 = np.array([11,12,13,14])
    pattern2 = np.array([14,13])
    trump_index = get_trump_index(hand_numbers)
    result = [check_pattern(hand_numbers,i,(pattern4 if i == trump_index else pattern2)) for i in np.array([1,2,3,4])]
    print(result) 
    return np.all(result)

def case_4(hand_numbers):
    pattern4 = np.array([12,13,14])
    pattern2 = np.array([14,13])
    trump_index = get_trump_index(hand_numbers)
    trump_cards = get_cards_by_suit(hand_numbers, trump_index)
    c = np.size(trump_cards)
    print(c)
    print(trump_cards)
    results = check_pattern(hand_numbers,trump_index, pattern4)
    print(results)
    a = c >= 5 and results
    return a



print("Hand3:", case_4(test2))  


4
[413 414 411 412]
Ранги карт: [13 14 11 12]
 DDDD True
True
Hand3: False


# сумарний ранг карт
ідея : в залежності від кількості карт ми можемо визначити мінімальний ранг карт цієї масті для того щоб ця комбінація була виграшною у розрізі цієї масті

 тобто напр: 
 - якщо в нас є 1 катра - туз : виграшна комбінація
 - якщо 2 карти - виграшна комбінація туз та король
 - і тд  
 
 тобто ми у розрізі масті розраховуємо сумарний ранг карт та визначаємо кількість карт цієї масті
 
 вважаєма що розклад карт цієї масті є виграшом якщо сумарний ранг карт цієї масті більше або = мінімальному рангу для цієї кількості.


In [ ]:

import numpy as np 

test1 = np.array([108,208,308,408 ])  
test2 = np.array([311, 112, 213, 314, 413, 209, 111, 107, 414,411, 412])
test3 = np.array([313, 113, 407, 213, 314, 413, 214, 114, 414,411, 412])
test4 = np.array([114, 112, 111, 109, 108, 214, 213])
test5 = np.array([312, 308, 114, 214, 313, 113, 311, 310, 413, 414])

def get_cards_by_suit(hand_numbers, suit_index):
    return hand_numbers[ hand_numbers // 100 == suit_index]

def check_winning_combination(hand_numbers,suit_index):
    #розрахувати сумарний ранг та кількість карт у розрізі масті
    dd = get_cards_by_suit(hand_numbers,suit_index)
    dd = np.sort(dd)[::-1]
    #print(dd)
    numbers_of_cards = np.size(dd)
    #print(ff_size)
    rang = np.sum(dd%100)
    
    #print(rang)
    # мінімальний ранг для виграшу 39 для 3 карт туз король дама
    # індекс в масиві це кількість карт
    min_rangs = np.array([ 0, 14, 27, 39, 50, 54, 61, 71, 84])
    min_rang_for_hand = min_rangs[numbers_of_cards]
    number_of_top_cards = numbers_of_cards if numbers_of_cards <=4 else 8 - numbers_of_cards
    rang_top_cards = np.sum(dd[:number_of_top_cards] %100)
    min_rang_for_top_cards = min_rangs[number_of_top_cards]
   # print(min_rang_for_top_cards,rang_top_cards,number_of_top_cards,numbers_of_cards)
    #print(min_rang_for_hand)

    return rang >= min_rang_for_hand and  rang_top_cards >= min_rang_for_top_cards




def case_5(hand_numbers):
    # знайдемо хочаб 1 масть з кількістю 4 або більше карт однієї масті
     

    r = np.array([
        check_winning_combination(hand_numbers,1),
        check_winning_combination(hand_numbers,2),
        check_winning_combination(hand_numbers,3),
        check_winning_combination(hand_numbers,4)
    ])
    #print(r)
    return np.all(r)


print("test1(повинно бути False):", case_5(test1))  
print("test2(повинно бути False):", case_5(test2)) 
print("test3(повинно бути True):", case_5(test3)) 
print("test4(повинно бути False):", case_5(test4)) 
print("test5:(повинно бути False)", case_5(test5))



test1(повинно бути False): False
test2(повинно бути False): False
test3(повинно бути True): True
test4(повинно бути False): False
test5:(повинно бути False) False


In [67]:
import numpy as np 

test1 = np.array([108,208,308,408 ])  
test2 = np.array([311, 112, 213, 314, 413, 209, 111, 107, 414,411, 412])
test3 = np.array([313, 113, 407, 213, 314, 413, 214, 114, 414,411, 412])
test3 = np.sort(test3)[::-1]
dd = np.size(test1)
print(f"dd = {dd}")

def case_5(hand_numbers):
    if not np.any(np.bincount(hand_numbers//100)>=4):
        return False
    
    r = np.array([
        check_winning_combination(hand_numbers,1),
        check_winning_combination(hand_numbers,2),
        check_winning_combination(hand_numbers,3),
        check_winning_combination(hand_numbers,4)
    ])
    print(r)
    return np.all(r)

print(case_5(test2))



dd = 4
[False False False  True]
False
