In [ ]:
import numpy as np

mat = np.array([
    [8, 1, 6],
    [3, 5, 7],
    [4, 9, 3]
])
#target_sum = np.sum(mat)
row_sums = np.sum(mat, axis=1)
print(row_sums)


[15 17 16]


In [33]:
np.all(np.array([9, 7, 9]) == 9)

np.False_

In [ ]:
import numpy as np

d =np.array( [ 
    2,3,4,
    5,6,2
] )

j =np.array( [ 
    True,True,False
] )

print(np.all(d))
print(np.all(j))


True
False


In [93]:
import numpy as np
#np.array([1,2,3,4,5])
#np.arange(107,120)# видає рангі карт
#np.arange(7,15)+200
d = np.array([np.arange(7,15)+100, np.arange(7,15)+200, np.arange(7,15)+300, np.arange(7,15)+400])#двумерний масив с рартами по масти
d = d.flatten()#плоский масив с колодой картю
#print(d)
#print(np.random.permutation(d))
s = np.random.permutation(d)
print(s)
player = s[:3]
s = s[3:]
print(s)
player002 = s[:3]
s = s[3:]
print("колода", s)
print(player)
print(player002)





[213 308 108 307 212 113 413 414 313 211 111 209 210 207 312 310 208 109
 114 408 309 412 112 314 410 110 411 214 107 311 409 407]
[307 212 113 413 414 313 211 111 209 210 207 312 310 208 109 114 408 309
 412 112 314 410 110 411 214 107 311 409 407]
колода [413 414 313 211 111 209 210 207 312 310 208 109 114 408 309 412 112 314
 410 110 411 214 107 311 409 407]
[213 308 108]
[307 212 113]


In [146]:
import numpy as np
# несколоко колод карт

num_players = 4   # кількість гравців
num_cards = 3     #кількість розданих карт 
num_decks = 5

num_decks = np.array([np.arange(7,15)+100, np.arange(7,15)+200, np.arange(7,15)+300, np.arange(7,15)+400])#двумерний масив с рартами по масти
num_decks = num_decks.flatten()#плоский масив с колодой картю
s = np.random.permutation(num_decks)
print(s)


for i in range(num_players):
    player = s[:num_cards]   # беремо перші k карт
    s = s[num_cards:]        # зменшуємо колоду
    print(f"Гравець {i+1} отримав:", player)
    print("Залишок у колоді:", s)


[411 212 110 207 312 209 113 111 310 114 412 308 112 307 211 413 314 408
 210 309 410 208 214 409 313 213 414 407 108 109 311 107]
Гравець 1 отримав: [411 212 110]
Залишок у колоді: [207 312 209 113 111 310 114 412 308 112 307 211 413 314 408 210 309 410
 208 214 409 313 213 414 407 108 109 311 107]
Гравець 2 отримав: [207 312 209]
Залишок у колоді: [113 111 310 114 412 308 112 307 211 413 314 408 210 309 410 208 214 409
 313 213 414 407 108 109 311 107]
Гравець 3 отримав: [113 111 310]
Залишок у колоді: [114 412 308 112 307 211 413 314 408 210 309 410 208 214 409 313 213 414
 407 108 109 311 107]
Гравець 4 отримав: [114 412 308]
Залишок у колоді: [112 307 211 413 314 408 210 309 410 208 214 409 313 213 414 407 108 109
 311 107]


In [ ]:
import numpy as np
# 
# приклад з tile
#d = None
d =np.array([1,2,3,4,5,6,7,8])
g= np.tile(d,(10,1))
s = np.array([np.random.permutation(a) for a in g])
print(s)
print(s[:,:3])
print(s[:,3:])


a =np.array([[1],[2],[3]])
#print(np.random.permutation(a))

[[4 1 6 3 2 8 5 7]
 [5 8 2 7 3 1 4 6]
 [1 7 4 6 5 3 2 8]
 [6 4 2 7 8 3 5 1]
 [4 1 7 8 3 2 6 5]
 [6 7 3 1 5 2 4 8]
 [1 8 6 4 3 2 5 7]
 [6 2 5 1 8 4 7 3]
 [5 3 4 8 2 7 6 1]
 [8 1 7 3 2 5 4 6]]
[[4 1 6]
 [5 8 2]
 [1 7 4]
 [6 4 2]
 [4 1 7]
 [6 7 3]
 [1 8 6]
 [6 2 5]
 [5 3 4]
 [8 1 7]]
[[3 2 8 5 7]
 [7 3 1 4 6]
 [6 5 3 2 8]
 [7 8 3 5 1]
 [8 3 2 6 5]
 [1 5 2 4 8]
 [4 3 2 5 7]
 [1 8 4 7 3]
 [8 2 7 6 1]
 [3 2 5 4 6]]
